# ============================
# HTCondor submission file
# ============================

# To be modified for each submission:
# log folder name (remember to create it via mkdir -p log_folder_name)
# executable
# number of CPUs
# job flavour or max run time
# seed file for queue

log_folder = logs_DA_MA

executable            = /afs/cern.ch/user/l/lsievert/htcondor_submissions/executable_DA_MA_ideal.sh
#arguments             = $(seed)

# Input files to transfer
transfer_input_files  = /afs/cern.ch/user/l/lsievert/htcondor_submissions/fcc-2026-afs.tar.gz

# Output and log
output                = $(log_folder)/out_ideal.txt
error                 = $(log_folder)/err_ideal.txt
log                   = log.txt

# Resources
request_CPUs          = 4

# One can either specify the Max Run time of the simulation in seconds or can use some of the keywords
# espresso = 20 minutes
# microcentury = 1 hour
# longlunch = 2 hours
# workday = 8 hours
# tomorrow = 1 day
# testmatch = 3 days
# nextweek = 1 week

#+JobFlavour           = "espresso"
+MaxRuntime           = 120000
#+MaxRuntime = 120000

queue
