# ============================
# HTCondor submission file
# ============================
# For submission on htcondor, the following documents are needed:
# this submission script
# the executable script
# a python environment (see details below)
# the code script to be run (called inside the executable file)

# The submission script, the executable script and the python environment are stored inside the htcondor_submissions folder on afs.
# The code script to be run is stored on eos.
# In order to submit from afs, use the command condor_submit submission_script_name
# In order to check the status of the submission, use condor_q
# The results are then to appear in the eos folder specified in the executable script.
# Note that whilst this setup works for the specific demands of the code scripts used here, more sophisticatd htcondor submission setups exist!

# To be modified for each submission:
# log folder name (remember to create it inside the htcondor_submissions folder using mkdir -p logs_orbit_correction)
# executable name and file path
# need to make sure the python environment is stored inside htcondor_submissions - this can be done by:
#           conda install conda-pack
#           conda-pack -n fcc-2026 -o fcc-2026-afs.tar.gz 
#           (where fcc-2026 is the name of the virtual environment that is exported as a zip file)
# number of CPUs
# job flavour or max run time
# seed file name (remember to create it inside the htcondor_submission folder: each line in the seed file should contain one seed number)


log_folder = logs_orbit_correction

executable            = /afs/cern.ch/user/l/lsievert/htcondor_submissions/executable_orbit_correction.sh
arguments             = $(seed)

# Input files to transfer
transfer_input_files  = /afs/cern.ch/user/l/lsievert/htcondor_submissions/fcc-2026-afs.tar.gz

# Output and log
output = $(log_folder)/out_$(seed).txt
error  = $(log_folder)/err_$(seed).txt
log    = log.txt

# Resources
request_CPUs          = 4

# One can either specify the Max Run time of the simulation in seconds or can use some of the keywords
# espresso = 20 minutes
# microcentury = 1 hour
# longlunch = 2 hours
# workday = 8 hours
# tomorrow = 1 day
# testmatch = 3 days
# nextweek = 1 week

#+JobFlavour           = "espresso"
+MaxRuntime           = 5400

# Queue jobs for each seed
#queue seed from successful_seeds_all.txt
queue seed from seeds1-200.txt
#queue seed from seeds_test.txt
